Refactoring
106-inc/Triangles pull request #24
Opened 2022-04-21 21:53 UTC by Tako-San

2022-04-21 21:53 UTC, Tako-San commented
Add ref-ref qualified methods

2022-04-21 21:54 UTC, Tako-San reviewed
Add ref-ref annotated methods

2022-04-23 11:28 UTC, derzhavin3016 requested changes

2022-04-23 11:28 UTC, derzhavin3016 commented on include/intersection/detail.hh
> +                      [fst](auto &&elt) { return (elt > 0) != fst || elt == 0; });
Comparing floating point using `==` operator

2022-04-23 11:57 UTC, derzhavin3016 commented
Remove Threshold manipulation from Vec3 class

2022-04-23 14:30 UTC, Tako-San commented
Maybe make macros for BoundBox `min` and `max` methods?

2022-04-23 14:43 UTC, Tako-San commented
> Maybe make macros for BoundBox `min` and `max` methods?

And add ref-ref qualified versions

2022-04-23 17:36 UTC, Tako-San commented
Make tests build unnecessary

2022-04-24 22:42 UTC, Tako-San commented
@derzhavin3016 finish your threshold idea and I think this pr will be ready to merge

2022-04-26 19:41 UTC, Tako-San commented on include/intersection/detail.hh
> +  std::transform(tr.begin(), tr.end(), dotArr.begin(), [&d](auto &&v) { return dot(d, v); });
Is it possible to use std::bind_front?

2022-04-26 19:41 UTC, Tako-San commented on include/intersection/detail.hh
>      lenArr[i] = (tr[i] - tr[i + 1]).length2();
Maybe use std:: transform?

2022-04-26 19:43 UTC, Tako-San commented on include/intersection/detail.hh
>      lenArr[i] = (tr[i] - tr[i + 1]).length2();
Looks like it is impossible

2022-04-28 19:22 UTC, Tako-San commented
https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/primitives/vec3.hh#L155
Add && version

2022-04-28 19:30 UTC, Tako-San commented
Looks like here works rule of zero
https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/container.hh#L24-L29

https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/container.hh#L66-L72

https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/kdtree.hh#L100-L106

2022-05-02 16:37 UTC, Tako-San reviewed
Maybe use std::bitcast instead of reinterpret_cast?

2022-05-02 19:41 UTC, derzhavin3016 commented
> Maybe use std::bitcast instead of reinterpret_cast?

@Tako-San, could you specify a place in code?

2022-05-02 19:42 UTC, Tako-San commented
> > Maybe use std::bitcast instead of reinterpret_cast?
> 
> @Tako-San, could you specify a place in code?

Node dump

2022-05-02 23:19 UTC, derzhavin3016 commented
> Looks like here works rule of zero
> 
> https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/container.hh#L24-L29
> 
> https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/container.hh#L66-L72
> 
> https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/kdtree.hh#L100-L106
> 
> UPD: Done

In this case compiler with option `-Weffc++` signalizes that class has pointer data members but does not decalre copy ctor & assignment. So, I suppose, it's better to default them

2022-05-02 23:36 UTC, derzhavin3016 commented on include/intersection/detail.hh
> +                      [fst](auto &&elt) { return (elt > 0) != fst || elt == 0; });
Fixed

2022-05-03 00:08 UTC, derzhavin3016 commented
> @derzhavin3016 finish your threshold idea and I think this pr will be ready to merge

Done.
Idk why, but unit test was failing on pipeline, but not on my machine. I fixed it by multiplying threshold on 100 (instead of 1000 in vector)

2022-05-03 07:05 UTC, Tako-San commented
> > @derzhavin3016 finish your threshold idea and I think this pr will be ready to merge
> 
> Done. Idk why, but unit test was failing on pipeline, but not on my machine. I fixed it by multiplying threshold on 100 (instead of 1000 in vector)

I checked your commits, LGTM. I tried to find the reason, but I don’t know why threshold causes such troubles.

2022-05-03 07:10 UTC, Tako-San commented
> > Looks like here works rule of zero
> > https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/container.hh#L24-L29
> > 
> > https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/container.hh#L66-L72
> > 
> > https://github.com/106-inc/Triangles/blob/6752b0b00353d866e05ba3762e37872ca2f52329/include/kdtree/kdtree.hh#L100-L106
> > 
> > UPD: Done
> 
> In this case compiler with option `-Weffc++` signalizes that class has pointer data members but does not decalre copy ctor & assignment. So, I suppose, it's better to default them

All of them is non-owning pointer, so no need to care about memory
We may return declarations if you wish

2022-05-06 08:49 UTC, Tako-San commented
https://github.com/106-inc/Triangles/blob/052abeb0aba04620be553945bfd2f1bcee92d459/include/kdtree/container.hh#L82

Looks like we may use `= default` here

2022-05-09 08:02 UTC, merged